name: manual trigger

on:
  workflow_dispatch:
    inputs:
      foo: 'bar'
jobs:
  hello:
    name: greeting
    runs-on: ubuntu-latest
    steps:
      
      - name: hello
        run: echo hello ${{ github.payload }}