name: manual trigger
on:
  issues:
    types: [opened]
jobs:
  say_hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello ${{ github.event.inputs.foo }}"