name: manual trigger
on:
  workflow_dispatch:
    inputs:
      foo: 'bar'
jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello ${{ github.event.inputs.foo }}"