- name: Semantic Releaser
  uses: brpaz/action-semantic-release@v1
  with:
    # Specifies a list of extra plugins to install
    install_plugins: # optional
    # Run semantic release in dry-run mode
    dry_run: # optional, default is false
    # The branch to release from
    branch: # optional, default is master
