name: Pull request 

on: pull_request  

jobs:
  lint_test_build:
    name: lint, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
            
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: npm install
        run: npm install
      
      - name: lint
        run: npm run lint

      - name: test
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # this is just an example, this could be any command that will trigger jest
          test-command: "yarn test"


      - name: build
        run: npm run build

      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info